bug-fix and refactoring view model
knowitrickard/FlexiCharge-Cross-Platform pull request #193
Opened 2022-10-07 17:14 UTC by Melesab

2022-10-07 20:05 UTC, ThorinEk approved these changes
Changes looks good! I think the TextEditingController variables should be moved to the ViewModel.

2022-10-10 07:27 UTC, SeitansPilgrim requested changes
Good job Meles!

2022-10-10 07:59 UTC, Magoulo approved these changes
looks good, good job

2022-10-10 08:08 UTC, SeitansPilgrim approved these changes

2022-10-10 08:25 UTC, merged