163 fix overflow issue in verify account view
knowitrickard/FlexiCharge-Cross-Platform pull request #199
Opened 2022-10-08 12:29 UTC by Melesab

2022-10-08 12:31 UTC, ThorinEk approved these changes
Looks great! :)

2022-10-08 13:43 UTC, willemannen approved these changes

2022-10-10 07:43 UTC, SeitansPilgrim requested changes
VERIFICATION_CODE_LENGTH does not follow naming conventions.

2022-10-10 08:26 UTC, Magoulo approved these changes

2022-10-10 08:27 UTC, merged